- cypress/drafts/sms_gateway/Add_bulksms_gateway.feature
- cypress/drafts/sms_gateway/Add_clickatell_gateway.feature
- cypress/drafts/sms_gateway/Add_generic_gateway.feature
- cypress/drafts/sms_gateway/Delete_gateway.feature
- cypress/drafts/sms_gateway/Generic_gateway_custom_key-value_pairs.feature
- cypress/drafts/sms_gateway/List_gateways.feature
- cypress/drafts/sms_gateway/Update_gateway.feature
This PR will add the feature files that describe the behavior of the "SMS Gateway" (previously "Gateway Configuration") section.
I don't know what's planned here. I'd propose we do changes like these in a different interation. The quickest way to move all core-apps to the platform stack is by not changing anything.
Not sure what this should do. Can this be en-/disabled per key/value per or is it a setting for the gateway itself?
> test(sms configuration): add draft feature files

- i18n/en.pot
- src/views/gateway_configuration/GatewayConfigFormEdit.js
- src/views/gateway_configuration/GatewayConfigList.js
- src/views/received_sms_list/ReceivedSmsList.js
- src/views/sent_sms_list/SentSmsList.js
- src/views/sms_commands/SmsCommandFormEdit.js
- src/views/sms_commands/SmsCommandList.js
- src/views/sms_commands/SmsCommandList.module.css
This adds a couple of fallbacks in case we get back unexpected data.
Notes
- For the SmsCommandFormEdit it's still possible to have a recognised parser type, but not have a case for that type. Ideally that should also be covered.
> fix: handle missing data

- src/smsCommandFields/FieldDataElementWithCategoryOptionComboFormula.js
The submit event from the form submit button couldn't be caught be the form, because the form wasn't a parent of the button. So I've moved the form up in the hierarchy, wrapping all the modal children, so that we can still use all the modal components for styling, whilst also allowing the form to catch the event. I checked the styling and it's the same as it was before this change.
> fix: wrap modal children in form to fix submit

- src/App.js
- src/views/NoMatch.js
- src/views/index.js
Note: this should eventually be merged to the patch branch, I assume. Which we should talk to Phil about first.
I'm using the approach used in the [import-export app](https://github.com/dhis2/import-export-app/blob/master/src/components/Router/Router.js) as well, which uses a hash router. All unmatched routes are redirected to home, so I've removed the NoMatch view.
> fix: routing

- src/dataSet/FieldDataSetWithAutoLoad.js
- src/program/FieldProgramWithAutoLoad.js
- src/programStage/FieldProgramStageWithAutoLoad.js
- src/smsCommand/useCreateSmsCommandMutation.js
- src/smsCommandFields/FieldCommandParser.js
- src/userGroup/FieldUserGroupWithAutoLoad.js
- src/views/sms_commands/SmsCommandFormNew.js
Fixed DHIS2-9478
- Adds the program stage field to the sms commands when "Event registration parser" is chosen.
- Sends the program stage to the `smsCommands` endpoint when "Event registration parser" is chosen
- Makes all fields required when adding a new sms command
> fix(event registration sms command form): add program stage field

- src/notifications/AlertHandler.js
Closes #53 
During testing I encountered an error warning for identical keys, which occurs when you have multiple alerts with the same message. I'm adding a timestamp to ensure unique keys.
> fix: add timestamp to fix duplicate message keys

- i18n/en.pot
- src/program/FieldProgramWithAutoLoad.js
- src/program/useReadProgramsQuery.js
- src/programStage/FieldProgramStage.js
- src/programStage/FieldProgramStageWithLoadingStates.js
- src/programStage/index.js
- src/views/sms_commands/SmsCommandFormNew.js
**Program stage select issue**
When selecting the `Program stage data entry parser` or `Tracked entity registration parser` first, everything behaves as it should. When selecting the `Event registration parser` and select both a program and a program stage, after changing to another parser type that uses programs & program stages (currently only `Program stage data entry parser), the program stage select's dropdown doesn't use the full width of the select anymore.
> fix(new sms cmd form): use correct value for program registration

- src/views/received_sms_list/SmsTable.js
Checks for existence of `user.userCredentials` instead of just `user` on the individual `message` objects.
Haven't changed any translations, must be leftovers from a previous change
> fix(received sms): check userCredentials exitence instead of its parent

- i18n/en.pot
- src/gateways/GatewayGenericForm.js
https://jira.dhis2.org/browse/DHIS2-9583
Since the [docs](https://docs.dhis2.org/master/en/dhis2_developer_manual/web-api.html#generic-http) are not clear (to me) about what the key value pairs do precisely, I've removed the text for now.
> fix: remove explanatory text

- i18n/en.pot
- src/forms/createEqualTo.js
- src/forms/index.js
- src/gateways/GatewayKeyValuePair.js
- src/gateways/GatewayKeyValuePair.module.css
- src/gateways/GatewayKeyValuePairConfidentialValueFields.js
- src/gateways/GatewayKeyValuePairConfidentialValueFields.module.css
- src/gateways/GatewayKeyValuePairValue.js
- src/gateways/GatewayKeyValuePairValueField.js
This will make sure that credential fields of key value pairs are of type password and adds a confirmation field.
I had to copy the `createEqualTo` form validator's code as it doesn't resolve paths, just play keys, while final form can handles paths. I'll create a UI issue for that, we could copy the code I've added in this PR to the UI's validator as well.
> feat(credential keyvalue pair): change credential field to type password

- i18n/en.pot
- src/gateways/FieldGatewayConfigurationTemplate.js
- src/gateways/FieldGatewayContentType.js
- src/gateways/FieldGatewaySendUrlParameters.js
- src/gateways/FieldGatewayUseGet.js
- src/gateways/GatewayGenericForm.js
- src/gateways/createGenericGateWayDataFromVariables.js
- src/gateways/useCreateGenericGatewayMutation.js
- src/gateways/useUpdateGenericGatewayMutation.js
This add 4 new fields to the generic gateway form:
* Configuration template
* Content type
* Use get
* Send url parameters
A proper description can be found in the [api docs](https://docs.dhis2.org/master/en/dhis2_developer_manual/web-api.html#generic-http)
> feat(generic gateway): add 4 missing fields to form

- src/gateways/FieldGatewayPasswordConfirmation.js
- src/views/gateway_configuration/GatewayConfigFormEdit.js
Fixes DHIS2-9598
Sets the initial value of the password confirmation field to the value of the actual password if the gateway type is bulksms.
> fix(bulk sms): set initial value of pw confirmation to actual pw

- src/views/received_sms_list/ReceivedSmsList.js
This was a case of me doing too much work. You can actually pass an array of filters to the data query and that will make sure each filter is prefixed with `filter=` and it will separate them with an `&`. So me joining the filters into a string was a bad idea.
> fix: make sure each filter param gets prefixed with 'filter='

- src/smsCommandFields/FieldDataElementWithCategoryOptionComboAddFormulaButton.js
- src/smsCommandFields/FieldDataElementWithCategoryOptionComboFormula.js
Fixes DHIS2-9905
Fixes the broken formula functionality.
To check:
1. go to sms commands
1. edit a j2me command
1. scroll down to the short codes
1. add a value to a code (to enable the formula button)
1. add, save, modify, remove formula
> fix(short code formula): use dataElement id instead of non-existing code

- src/smsCommandFields/FieldDataElementWithCategoryOptionComboAddFormulaButton.js
Currently the component responsible for this only loaded the name of the data element once, which obviously is wrong:
Changing the data element of a formula did not have a visual effect (it has been saved correctly though)
How to reproduce:
1. Go to sms configuration app
1. Go to commands section
1. Create a J2ME command if not existing yet
1. Edit a J2ME command 
1. Add a value to one of the short codes if there is no short code with a value yet
1. Add a formula to a short code with a value if there's no short code with a formula yet
1. Change the data element of the formula
1. Save the changes
1. The newly chosen data element's name is not displayed below the short code's value input field. Instead the old one is still being shown
> fix(sms commands): show correct formula after update [DHIS2-9932]

- src/views/sent_sms_list/SentSmsList.module.css
`align-items: flex-end` is better supported than `align-items: end` according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#support_in_flex_layout) and Firefox Dev Tools:
> fix(sent sms list): use flex-end instead of end

- CODEOWNERS
- d2.config.js
Align all our application versions that range between 0.x.x and 36.x.x
with different semantics to a single version scheme with distinct
semantics for what constitutes a breaking change.
We have chosen to bump to v100.0.0 to signify the depature from the old
version scheme to the new.
For more information:
dhis2/notes#293
BREAKING CHANGE: App version becomes decoupled from DHIS2 versions, see
the d2.config.js or App Hub for DHIS2 version compatibility.
> chore(release): migrate to new app version scheme

- src/sms-command/DataElementTimesCategoryOptionCombos/DataElementTimesCategoryOptionCombos.js
- src/sms-command/FieldDataElementWithCategoryOptionCombo/FieldDataElementWithCategoryOptionCombo.js
- src/sms-command/FormJ2meParser/Form.js
- src/sms-command/FormJ2meParser/FormJ2meParser.js
- src/sms-command/FormJ2meParser/getInitialFormState.js
- src/sms-command/FormJ2meParser/useCommandData.js
- src/sms-command/FormJ2meParser/useUpdateCommandMutation.js
- src/sms-command/FormKeyValueParser/Form.js
- src/sms-command/FormKeyValueParser/FormKeyValueParser.js
- src/sms-command/FormKeyValueParser/getInitialFormState.js
- src/sms-command/FormKeyValueParser/useCommandData.js
- src/sms-command/FormKeyValueParser/useUpdateCommandMutation.js
Fixes a bug in key value pair & J2ME sms commands which rendered the wrong input fields for short codes.
Impacts covid vaccination sms commands
> fix(sms key value parser commands): create short code input fields correclty

- src/shared/components/pagination/Pagination.js
Fix for [BETA-50](https://dhis2.atlassian.net/browse/BETA-50)
Prevents app from erroring out when there are no received/sent messages (issue was caused by pagination, so this is hidden when pageCount===0)
Note the api is returning `pageCount: 0` and `page: 1` which is why the error occurs (we had a SingleSelect where we set the selected page as `page` and then it could not select that as the pageCount is 0).
With this fix, we just don't render anything if the api says the pageCount is 0. This works even when you delete the values from the table because the query is re-executed and you get the updated pageCount.
**Before**
App errors out (see ticket)
**After**
Table without paginator 
[BETA-50]: https://dhis2.atlassian.net/browse/BETA-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> fix: hide pagination when pageCount==0

- i18n/en.pot
- i18n/fr.po
- src/sms-command/DataElementTimesCategoryOptionCombos/CompletenessMessage.js
- src/sms-gateway/ViewSmsGatewayList/ViewSmsGatewayList.js
From ticket: https://dhis2.atlassian.net/browse/DHIS2-10931
I checked the app (in French) and it looks like most of the strings are covered to allow for translations.
I fixed:
- A missing translation of a Header (the translation itself existed already in French):
_Before/After_
- A message where the string wasn't being scanned because we hadn't interpolated the variable in the string (I've added the translation into French for testing (which would be overwritten if someone provided something else in Transfiex)):
_Before/After_
Other issues I noticed [could be separate tickets]:
- some default form values aren't translated 
But these come from the backend https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-api/src/main/java/org/hisp/dhis/sms/command/SMSCommand.java#L50
- validation …
> fix: add translation handling where missing [DHIS2-10931]

- package.json
- yarn.lock
this bumps (and resolves) ui version to 9.11.7 to pick up fix relating to selector layers: https://github.com/dhis2/ui/pull/1614
ticket: [DHIS2-18119](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-18119)
**Before**
**After**
[DHIS2-18119]: https://dhis2.atlassian.net/browse/DHIS2-18119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump ui version [DHIS2-18119]

- i18n/en.pot
- src/sms-inbound/ReceivedSmsTable/ReceivedSmsTable.js
- src/sms-inbound/ViewReceivedSmsList/ViewReceivedSmsList.js
This ticket ([DHIS2-18261](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-18261)) was to remove references to user.userCredential, but as it turns out `user` is not being returned for sms/inbound, and even if it were being returned it would not represent the sender of the sms (as we were showing in the app), but rather the creator of the metadata (I talked this over with Jan B. in slack conversation on team channel: https://dhis2.slack.com/archives/C05LL17C8AJ/p1733145814548449)
Consequently, I have just removed the reference to the user field and removed the relevant column
**Before**
**After**
(I'm not addressing any of the other obvious UI issues like the lack of margins on the search fields 🙈)
[DHIS2-18261]: …
> fix: remove user from smsInbound request [DHIS2-18261]
